name: epub_image_compressor
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # 状态管理 & 路由 & 网络
  get:
    git:
      url: "https://gitcode.com/openharmony-sig/fluttertpc_get.git"

  cached_network_image: ^3.4.1

  # 本地存储
  shared_preferences:
    git:
      url: "https://gitcode.com/openharmony-sig/flutter_packages.git"
      path: "packages/shared_preferences/shared_preferences"
      ref: "br_shared_preferences-v2.3.2_ohos"
  path_provider: ^2.1.1

  # 权限
  permission_handler:
    git:
      url: "https://gitcode.com/openharmony-sig/flutter_permission_handler.git"
      path: "permission_handler"
      ref: "br_permission_handler_v11.3.1_ohos"

  # UI 支撑
  flutter_screenutil: ^5.9.3
  pull_to_refresh: ^2.0.0
  flutter_smart_dialog: ^4.9.8+7

  # 加解密
  crypto: ^3.0.6
  encrypt: ^5.0.1

  # 数据库
  sqflite:
    git:
      url: "https://gitcode.com/openharmony-sig/flutter_sqflite.git"
      path: "sqflite"
  sqflite_common:
    git:
      url: "https://gitcode.com/openharmony-sig/flutter_sqflite.git"
      path: "sqflite_common"
  sqflite_common_ffi:
    git:
      url: "https://gitcode.com/openharmony-sig/flutter_sqflite.git"
      path: "sqflite_common_ffi"

  # 其他
  url_launcher: ^6.3.1
  archive: ^3.6.1
  image: ^4.2.0
  file_picker: ^8.1.2
  path: ^1.9.0
  window_manager: ^0.4.3

dependency_overrides:
  win32: 5.5.1
  sqflite:
    git:
      url: "https://gitcode.com/openharmony-sig/flutter_sqflite.git"
      path: "sqflite"
  path_provider:
    git:
      url: "https://gitcode.com/openharmony-tpc/flutter_packages.git"
      path: "packages/path_provider/path_provider"
      ref: "br_path_provider-v2.1.4_ohos"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
